CREATE SCHEMA IF NOT EXISTS user_service_schema AUTHORIZATION root;
CREATE SCHEMA IF NOT EXISTS bank_service_schema AUTHORIZATION root;
CREATE SCHEMA IF NOT EXISTS exchange_service_schema AUTHORIZATION root;
