global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "bank-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["bank-service:8082"]
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8080"]